name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set environment variable
        run: echo "VITE_HTTP_BASE_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: dist/
